openapi: 3.0.0
info:
  title: Mock MCP Server
  version: 1.0.0
paths:
  /jsonrpc:
    post:
      summary: MCP JSON-RPC endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success
          content:
            application/json:
              example:
                jsonrpc: "2.0"
                id: "1"
                result:
                  resources:
                    - id: "file-1"
                      name: "example.txt"
                      type: "file"
                  tools:
                    - id: "echo"
                      name: "Echo Tool"
                      description: "Returns input text."
